
server:
  port: 8084
  
  
spring :
  datasource :
#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.7.64:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    
    