server:
  port: 8087
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ojas_obs
#    password: root
#    username: root
    url: jdbc:mysql://192.168.6.186:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
