version: '3'
services:
  api-gateway:
    image: api-gateway
    ports:
     - "8089:8089"
  auth-center:
    image: auth-center
    depends_on:
     - api-gateway
    ports:    
    - "8081:8081"
  ojas-obs-cost-center:
   image :  ojas-obs-cost-center
   depends_on:
   - auth-center
   ports:
   - "8013:8013"
  ojas-obs-businessunit:
   image : ojas-obs-businessunit
   depends_on:
   - auth-center
   ports:
   - "8015:8015"
  ojas-obs-online-passport :
    image : ojas-obs-online-passport
    depends_on:
    - auth-center
    ports:
    - "8012:8012"
  ojas-obs-online-gpa:
    image : ojas-obs-online-gpa
    depends_on:
    - auth-center
    ports:
    - "8018:8018"
  ojas-obs-online-employeestatus-service :
    image : ojas-obs-online-employeestatus-service
    depends_on:
    - auth-center
    ports:
    - "8017:8017"
  ojas-obs-educationtype :
   image : ojas-obs-educationtype
   depends_on:
   - auth-center
   ports:
   - "8016:8016"
  ojas-obs-rolemanagement:
   image : ojas-obs-rolemanagement
   depends_on:
   - auth-center
   ports:
   - "8020:8020"
  ojas-obs-subbusinessunit :
   image : ojas-obs-subbusinessunit
   depends_on:
   - auth-center
   ports:
   - "8021:8021"
  ojas-obs-gender:
    image : ojas-obs-gender
    depends_on:
    - auth-center
    ports:
    - "8010:8010"
  ojas-obs-resource-type:
   image : ojas-obs-resource-type
   depends_on:
   - auth-center
   ports:
   - "8022:8022"
  ojas-obs-designation:
    image : ojas-obs-designation
    depends_on:
    - auth-center
    ports:
    - "8011:8011"
  ojas-obs-online-separationtype-service:
   image : ojas-obs-online-separationtype-service
   depends_on:
   - auth-center
   ports:
   - "8019:8019"
  ojas-obs-states :
   image : ojas-obs-states
   depends_on:
   - auth-center
   ports:
   - "8014:8014"
  ojas-obs-skill:
    image : ojas-obs-skill
    depends_on:
     - auth-center
    ports:
     - "8023:8023"
  ojas-obs-bankdetails:
    image: ojas-obs-bankdetails
    depends_on:
    - auth-center
    ports:
    - "9000:9000"
  ui-server:
     image: ui-server
     ports:
     - "8000:8000"