version: '3'
services:
  api-gateway:
    image: api-gateway
    ports:
     - "8089:8089"
  auth-center:
    image: auth-center
    depends_on:
     - api-gateway
    ports:    
    - "8081:8081"
  ojas-obs-cost-center:
   image :  ojas-obs-cost-center
   depends_on:
   - auth-center
   ports:
   - "8013:8013"
  ojas-obs-businessunit:
   image : ojas-obs-businessunit
   depends_on:
   - auth-center
   ports:
   - "8096:8096"
  ui-server:
     image: ui-server
     ports:
     - "8000:8000"