server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  profiles:    active:    - dev