#spring.datasource.driver-class-name= jdbc:mysql://localhost/ojas_obs
#spring.datasource.data-username= root
#spring.datasource.data-password= root
#spring.datasource.url= com.mysql.jdbc.Driver


# Here 'test' is the database name

server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://192.168.6.186:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
  
 #   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
 #   username: root
 #   password: sai@1234
 #   driver-class-name: com.mysql.jdbc.Driver