## MySQL jdbc connection url.
#spring.datasource.url=jdbc:mysql://localhost:3306/obs
# MySQL jdbc driver class name.
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# MySQL database username and password
#spring.datasource.username=root
#spring.datasource.password=root
server:
  port: 8092

#MySQL jdbc connection 
spring:
 datasource:
    url: jdbc:mysql://192.168.6.186:3306/ojas_obs?autoReconnect=true&useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver

#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
