server:
  port: 8089

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://192.168.6.186:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    ojas-obs-cost-center:
      path : /obs/costcenterservice/**
      url: http://192.168.6.186:8013/
    ojas-obs-businessunit :
      path : /obs/businessUnit/**
      url : http://192.168.6.186:8015/
    ojas-obs-online-passport:
      path : /obs/passportService/**
      url : http://192.168.6.186:8012/
    ojas-obs-online-gpa:
     path : /obs/gpa/**
     url : http://192.168.6.186:8018/
    ojas-obs-online-employeestatus-service:
     path : /obs/EmployeeStatus/**
     url : http://192.168.6.186:8017/
    ojas-obs-educationtype:
     path : /obs/educationdetails/**
     url : http://192.168.6.186:8016/
    ojas-obs-rolemanagement:
     path : /obs/RoleManagement/**
     url : http://192.168.6.186:8020/
    ojas-obs-subbusinessunit:
     path : /obs/subbusinessunit/**
     url : http://192.168.6.186:8021/
    ojas-obs-gender:
      path: /obs/genders/**
      url: http://192.168.6.186:8010/
    ojas-obs-states :
      path : /obs/states/**
      url : http://192.168.6.186:8014/
    ojas-obs-resource-type:
       path : /obs/resourceType/**
       url : http://192.168.6.186:8022/  
    ojas-obs-designation:
      path: /obs/designation/**
      url: http://192.168.6.186:8011/
    ojas-obs-online-separationtype-service :
     path : /obs/separationType/**
     url : http://192.168.6.186:8019/  
    ojas-obs-skill:
      path : /obs/skill/**
      url : http://192.168.6.186:8023/
    ojas-obs-bankdetails:
      path: /obs/BankDetails/**
      url: http://192.168.6.186:9000/
    ojas-obs-employee-education-details:
      path: /obs/employeeEducationDetails/**
      url: http://192.168.6.186:8525/
    ojas-obs-dependentdetails:
      path: /obs/DependentDetailsService/**
      url: http://192.168.6.186:8090/
    ojas-obs-employeebu:
     path: /obs/employeebu/**
     url: http://192.168.6.186:8087/
    ojas-obs-empcertificationdetails:
     path: /obs/certifications/**
     url: http://192.168.6.186:8888/ 
    ojas-obs-employeeexperiencedetails:
      path: /obs/EmployeeExperienceDetails/**
      url: http://192.168.6.186:8092/ 
    ojas-obs-employeecontactinfo:
      path: /obs/employeecontactinfo/**
      url: http://192.168.6.186:8091/
    ojas-obs-employeeskills:
      path: /obs/employeeskillsdetails/** 
      url: http://192.168.6.186:8094/ 
    ojas-obs-employment-details :
       path: /obs/employmentDetails/**
       url: http://192.168.6.186:8084/   
    ojas-obs-project-details:
       path: /obs/projectDetails/**
       url: http://192.168.6.186:8083/  
    ojas-obs-kye:
       path: /obs/kye/**
       url: http://192.168.6.186:7070/   
    ojas-obs-employeeinfo:
      path: /obs/employeeInfo/**
      url: http://192.168.6.186:8093/    
    ojas-obs-title:
      path: /obs/employeetitle/**
      url: http://192.168.6.186:8095/      
    #192.168.6.186
    
ojas.security.jwt.secret: otherpeopledontknowit
