server:
  port: 8525
spring:
  datasource:
   url: jdbc:mysql://192.168.7.64:3306/ojas_obs
   username: dbubora
   password: Ojas-1525
   driver-class-name: com.mysql.jdbc.Driver
   tomcat:
      max-wait-millis: 20000
      max-active: 3
      max-idle: 2
      min-idle: 1  
#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
