server:
  port: 5555
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ojas_obs
#    driver-class-name: com.mysql.jdbc.Driver
#    password: root
#    username: root

    url: jdbc:mysql://192.168.7.64:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver